"""Human-readable calculation and design reports for one pipeline run."""

from __future__ import annotations

from pathlib import Path

from gearen.io_utils import write_json
from gearen.models import (
    GearCandidate,
    GearboxRequirement,
    LayoutResult,
    OperatingParameters,
    RequirementReview,
    ValidationReport,
)


DISCLAIMER = (
    "本项目生成的是概念级参数化设计结果，不能直接用于制造、"
    "安全关键系统或工业认证。"
)


def write_reports(
    output_dir: Path,
    requirement: GearboxRequirement,
    review: RequirementReview,
    operating: OperatingParameters,
    candidate: GearCandidate,
    layout: LayoutResult,
    validation: ValidationReport,
    cad_files: list[Path],
) -> list[Path]:
    """Write calculation Markdown, validation JSON, and a concise design summary."""
    reports_dir = output_dir / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    calculation_path = reports_dir / "calculation_report.md"
    validation_path = reports_dir / "validation_report.json"
    summary_path = reports_dir / "design_summary.md"
    calculation_path.write_text(
        _calculation_markdown(operating, candidate), encoding="utf-8"
    )
    write_json(validation_path, validation)
    summary_path.write_text(
        _summary_markdown(
            requirement, review, candidate, layout, validation, cad_files
        ),
        encoding="utf-8",
    )
    return [calculation_path, validation_path, summary_path]


def _calculation_markdown(
    operating: OperatingParameters, candidate: GearCandidate
) -> str:
    """Render documented formulas and their selected-candidate values."""
    return f"""# Calculation Report

{DISCLAIMER}

## Operating parameters

- Output speed: `n2 = n1 / i = {operating.output_speed_rpm:.3f} rpm`
- Input torque: `T1 = 9550 P / n1 = {operating.input_torque_Nm:.3f} N·m`
- Ideal output torque: `{operating.ideal_output_torque_Nm:.3f} N·m`
- Estimated output torque at efficiency {operating.efficiency:.3f}:
  `{operating.estimated_output_torque_Nm:.3f} N·m`

## Selected MVP candidate

- Teeth: `z1={candidate.z1}`, `z2={candidate.z2}`
- Standard module: `{candidate.module_mm:g} mm`
- Face width: `{candidate.face_width_mm:g} mm`
- Actual ratio: `{candidate.actual_ratio:.6f}`
- Relative ratio error: `{candidate.ratio_error:.6%}`
- Pitch diameters: `{candidate.pitch_diameter_pinion_mm:.3f} mm`,
  `{candidate.pitch_diameter_wheel_mm:.3f} mm`
- Outside diameters: `{candidate.outside_diameter_pinion_mm:.3f} mm`,
  `{candidate.outside_diameter_wheel_mm:.3f} mm`
- Centre distance: `{candidate.centre_distance_mm:.3f} mm`
- Tangential force: `{candidate.tangential_force_N:.3f} N`
- Radial force at {candidate.pressure_angle_deg:g}°:
  `{candidate.radial_force_N:.3f} N`
- Ranking score: `{candidate.score:.6f}` (lower is preferred; heuristic only)

This report does not implement ISO 6336, bearing rating life, FEA, thermal
analysis, or a manufacturing release check.
"""


def _summary_markdown(
    requirement: GearboxRequirement,
    review: RequirementReview,
    candidate: GearCandidate,
    layout: LayoutResult,
    validation: ValidationReport,
    cad_files: list[Path],
) -> str:
    """Render decisions, traceability, limitations, and generated CAD paths."""
    unresolved = "\n".join(
        f"- {item}" for item in review.unresolved_requirements
    ) or "- 无"
    assumptions = "\n".join(
        f"- `{key}={value}`" for key, value in review.assumptions.items()
    )
    blocked = "\n".join(
        f"- {item.message}"
        for item in validation.checks
        if item.status == "blocked"
    ) or "- 无"
    provisional = "\n".join(
        f"- {item.message}"
        for item in validation.checks
        if item.status == "provisional"
    ) or "- 无"
    files = "\n".join(f"- `{path.name}`" for path in cad_files)
    bearing_rows = "\n".join(
        f"- `{item.component_id}`: {item.designation}, "
        f"{item.selection_status}/{item.life_check_status}"
        for item in layout.bearings
    )
    return f"""# Gearbox Design Summary

{DISCLAIMER}

## Requirement

{requirement.objective}

## Selected concept

- Single-stage parallel-axis external spur gear pair
- Teeth/module/width: `{candidate.z1}/{candidate.z2}`,
  `{candidate.module_mm:g} mm`, `{candidate.face_width_mm:g} mm`
- Centre distance: `{candidate.centre_distance_mm:.3f} mm`
- Design status: `{candidate.status}`
- Validation overall status: `{validation.overall_status}`

## Central assumptions

{assumptions}

## Unresolved requirements

{unresolved}

## Bearing selections

{bearing_rows}

## Blocked checks

{blocked}

## Provisional checks

{provisional}

## CAD artifacts

{files}

Interactive preview was not generated by the headless CLI. Open the exported
STEP assembly or STL in a CAD viewer.
"""

